repos:
-   repo: https://github.com/python/black
    rev: 20.8b1
    hooks:
    -   id: black
-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8
        additional_dependencies: [flake8-comprehensions>=3.1.0]
    -   id: flake8
        name: flake8-pyx
        files: \.(pyx|pxd)$
        types:
          - file
        args: [--append-config=flake8/cython.cfg]
    -   id: flake8
        name: flake8-pxd
        files: \.pxi\.in$
        types:
          - file
        args: [--append-config=flake8/cython-template.cfg]
-   repo: https://github.com/PyCQA/isort
    rev: 5.2.2
    hooks:
    -   id: isort
        exclude: ^pandas/__init__\.py$|^pandas/core/api\.py$
-   repo: https://github.com/asottile/pyupgrade
    rev: v2.7.2
    hooks:
    -   id: pyupgrade
        args: [--py37-plus]
-   repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.6.0
    hooks:
      - id: rst-backticks
        # these exclusions should be removed and the files fixed
        exclude: (?x)(
          text\.rst|
          timeseries\.rst|
          visualization\.rst|
          missing_data\.rst|
          options\.rst|
          reshaping\.rst|
          scale\.rst|
          merging\.rst|
          cookbook\.rst|
          enhancingperf\.rst|
          groupby\.rst|
          io\.rst|
          overview\.rst|
          panel\.rst|
          plotting\.rst|
          10min\.rst|
          basics\.rst|
          categorical\.rst|
          contributing\.rst|
          contributing_docstring\.rst|
          extending\.rst|
          ecosystem\.rst|
          comparison_with_sql\.rst|
          install\.rst|
          calculate_statistics\.rst|
          combine_dataframes\.rst|
          v0\.|
          v1\.0\.|
          v1\.1\.[012])
